### ISSUE TITLE
Course semester/year sorting

### ISSUE THREAD

**Issue by Tanner** [kmehan/gt-course-critique#10]
This is not particularly a bug, but just something I noted and it might be worth discussing the behavior.

When sorting descending, the years sort in descending order (as expected). The semesters could be argued that they are not in descending order, i.e. Fall, Summer, Spring.
![Screen Shot 2013-03-30 at 10 16 53 AM](https://f.cloud.github.com/assets/166744/320469/a5c348c8-9944-11e2-8f1d-acead513053e.png)

The same occurs when sorting ascending. The semesters do not sort.
![Screen Shot 2013-03-30 at 10 17 01 AM](https://f.cloud.github.com/assets/166744/320471/ad31e6f0-9944-11e2-9d11-5bbb8e7cfe25.png)

As I said, it is not particularly a bug, more of a behavior. Should the semesters also sort when sorting or should they remain in the same order, because we are really just sorting years? If so, is the latter clear?

**Comment by cobookman** [comment]
I can think of two ways for me to fix this without messing with the dataTables.js core.
A) Seperate year into two columns.  Year and Semester.
B) Change the formatting to be 2011 - Spring

Any preference?

**Comment by Tanner** [comment]
I think option A would be the best as you get the right behavior. Option B just makes the inconsistency less obvious.

**Comment by cobookman** [comment]
I'm referencing issue: https://github.com/cobookman/gt-course-critique/issues/5

~~As it'd now make sence to split the 'year' filter into two filters: semester, year~~

~~They'd also need to be correlated. (aka narrowing down by fall semester, shold also force the course list and year to filter down).~~

~~This is no longer a 'simple' fix, and will require complex logic.~~

**Comment by cobookman** [comment]
The fix is currently live on critique.gatech.edu, will be pushing out to github after finals (2 weeks).

The simple fix was to sort the hash table's keys. 

``` javascript
function genList(outID, elements) {
      var listOptions = '<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">'+outID+' <b class="caret"></b></a><ul id="'+outID+'" class="dropdown-menu">';
      //Sort keys of hashtable
      var keys = [];
      for(var key in elements) {
       if(elements.hasOwnProperty(key)) {
         keys.push(key);
       }
      }
      keys.sort();
      for(var i in keys) {
        listOptions += '<li><label for=\''+keys[i]+'\'><input id=\''+keys[i]+'\' type="checkbox" onclick="toggleAction(\''+keys[i]+'\', \''+outID+'\');" checked="true" />'+elements[keys[i]]+'</label></li>';
      }
      listOptions += "</ul></li>";
      $("div#dataTable_wrapper > div.row > div.span6:first > ul").append(listOptions);
    }
```
