### ISSUE TITLE
Include information from Summer and Fall 2013

### ISSUE THREAD

**Issue by c10ce** [kmehan/gt-course-critique#20]
When we have the information, we should update the production database for Course Critique to include the Summer and Fall semesters.

**Comment by c10ce** [comment]
[reddit](http://www.reddit.com/r/gatech/comments/1t5kto/anyone_know_when_course_critique_usually_gets/) was asking about it.

**Comment by c10ce** [comment]
Got pinged again on [reddit](http://www.reddit.com/r/gatech/comments/24wyjt/when_do_fall_2013_grades_come_up_on_course/)

**Comment by cobookman** [comment]
I'm no longer in charge of CC, but its a manual importation effort, and OIT constantly blocks the ElasticSearch VM from the Webhosting VM....so its not an easy operation.  Will inform the next CC SGA IT Specialist on what to do, when I get his/her name.

**Comment by c10ce** [comment]
@cobookman Would you happen to know when the next person be appointed: summer or fall?

**Comment by cobookman** [comment]
Sometime in the Fall.  Hopefully by the time that person is appointed, Fall 2013, Spring 2014, and Summer 2014 can all be put into the system at once....FERPA permitting.
