### ISSUE TITLE
Value of 'id' param should be escaped before use in prepared statement

### ISSUE THREAD

**Issue by mayankgupta** [kmehan/gt-course-critique#25]
The **id** param in course.php and prof.php should be escaped before use.
**LIKE** in PDO prepared statement with '%' as :id value ends up spewing all rows.

Steps to reproduce - 
Visit - http://critique.gatech.edu/prof.php?id=% or http://critique.gatech.edu/course.php?id=% (your browser might freeze).

**Comment by cobookman** [comment]
This isn't a security concern as PDO is binding the parameters (if possible), and has a fallback of escaping. 

As for a query of `%`, I'm not sure if its worth fixing.  The only way this could occur is if you physically modify the URL, and replace the querystring with `id=%`

**Comment by mayankgupta** [comment]
This can actually serve as a pot for DOS attacks. Servers with comparatively small computing capability, bandwidth can be soft targets.
