### ISSUE TITLE
No space between first and last name of professor

### ISSUE THREAD

**Issue by Tanner** [kmehan/gt-course-critique#4]
When on the course result page (i.e. course.php), the first and last name of all the professors are not separated by a space.

For example, on [this page](http://critique.gatech.edu/course.php?id=CS2200) `Conte,Thomas Martin` should be `Conte, Thomas Martin`.

Appears to be a database issue rather than a presentation issue.

**Comment by cobookman** [comment]
Fixed through database modification.
