### ISSUE TITLE
On professor page, possible to remove all classes

### ISSUE THREAD

**Issue by Tanner** [kmehan/gt-course-critique#8]
It is possible to remove all classes from the professor page via the Courses select.

It should not be possible.

**Comment by Tanner** [comment]
Won't fix?

**Comment by cobookman** [comment]
Minor bug, currently I don't have enough time to fix it.

**Comment by Tanner** [comment]
You should leave it open, so that it is not forgotten about when you have time and someone else will come along and fix it because they saw it was open.

**Comment by cobookman** [comment]
By implementing this feature, a lot of bug patches will become much more complex. For instance having a select all/deselect all.

Also this could confuse the end user.

As such, while I understand the reasoning for implementing this, I don't think its the best option. It'd make more sense to just display an empty row of 'No Courses Selected'.

Around the lines of:
http://critique.gatech.edu/course.php?id=MATH150

**Comment by Tanner** [comment]
A "No _ Selected" message sounds good to me.
